$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: 0.2
dictionaries:
  - allowed
  - forbidden
dictionaryDefinitions:
  - name: allowed
    path: https://raw.githubusercontent.com/verygoodopensource/very_good_dictionaries/main/allowed.txt
    description: Allowed spellings
  - name: forbidden
    path: https://raw.githubusercontent.com/verygoodopensource/very_good_dictionaries/main/forbidden.txt
    description: Forbidden spellings
useGitignore: false
ignorePaths: [dist, node_modules, plugins]
words:
  - aarch
  - aars
  - altool
  - apks
  - appcenter
  - astro
  - astrojs
  - boltman
  - bryanoltman
  - buildroot
  - canva
  - classpath
  - cmdline
  - cocoapods
  - codemagic
  - codepush
  - codesign
  - codesigning
  - elif
  - evenodd
  - ffigen
  - jank
  - janky
  - keyrings
  - libapp
  - libflutter
  - libglu
  - libstdc
  - libupdater
  - localappdata
  - logcat
  - longpaths
  - maclinux
  - microsoftonline
  - mipmap
  - mozallowfullscreen
  - nubank
  - outform
  - podfile
  - prefs
  - pubin
  - pubout
  - previewable
  - recompiles
  - riverpod
  - rollouts
  - rsassa
  - sdkman
  - seidel
  - shellenv
  - shorebirdtech
  - softwareupdate
  - subosito
  - temurin
  - uiscene
  - webkitallowfullscreen
  - widgetbook
  - xcarchive
  - xcframework
  - xcframeworks
  - xcrun
