$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: 0.2
dictionaries:
  - allowed
  - forbidden
dictionaryDefinitions:
  - name: allowed
    path: https://raw.githubusercontent.com/verygoodopensource/very_good_dictionaries/main/allowed.txt
    description: Allowed spellings
  - name: forbidden
    path: https://raw.githubusercontent.com/verygoodopensource/very_good_dictionaries/main/forbidden.txt
    description: Forbidden spellings
useGitignore: false
ignorePaths:
  - dist
  - node_modules
  - package-lock.json
  - plugins
  - '**/*.svg'
words:
  - aarch
  - aars
  - altool
  - angelov
  - appname
  - apks
  - appcenter
  - applebot
  - astro
  - astrojs
  - bingbot
  - boltman
  - bryanoltman
  - buildroot
  - bytespider
  - canva
  - classpath
  - cmdline
  - cocoapods
  - codemagic
  - codepush
  - cohere
  - corsa
  - cloudkms
  - codesign
  - codesigning
  - cupertino
  - elif
  - emailaddress
  - eseidel
  - evenodd
  - externalagent
  - ffigen
  - fintech
  - frontmatter
  - gallego
  - gles
  - graphql
  - geocodes
  - hotfixes
  - idfa
  - idfv
  - jank
  - janky
  - lateinit
  - keyrings
  - linearapp
  - linkset
  - lavamoat
  - libapp
  - libexec
  - libflutter
  - libglu
  - libstdc
  - libupdater
  - llms
  - lobanov
  - localappdata
  - logcat
  - longpaths
  - maclinux
  - meteo
  - microsoftonline
  - mortems
  - mipmap
  - mobileprovision
  - mozallowfullscreen
  - notlike
  - nubank
  - opengraph
  - opensearch
  - opensearchdescription
  - outform
  - paweł
  - pixelmator
  - podfile
  - podhelper
  - prefs
  - pubin
  - pubout
  - previewable
  - recompiles
  - riverpod
  - rollouts
  - rsassa
  - sdkman
  - seidel
  - shellenv
  - shorebirdtech
  - softwareupdate
  - squircle
  - squircles
  - subclassing
  - subosito
  - superellipse
  - subview
  - tabler
  - temurin
  - tweens
  - twoslash
  - trafficadvice
  - uiscene
  - vsync
  - vvago
  - wagus
  - yourcompany
  - webkitallowfullscreen
  - widgetbook
  - wikidata
  - wordmark
  - xcarchive
  - xcframework
  - xcframeworks
  - xcrun
ignoreWords:
  - timezone
